include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MyDebugToolPrefs
MyDebugToolPrefs_FILES = layout.xml
MyDebugToolPrefs_INSTALL_PATH = /Library/PreferenceBundles
MyDebugToolPrefs_FRAMEWORKS = UIKit
MyDebugToolPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS)/makefiles/bundle.mk
