include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MyDebugToolPrefs

# ✅ 补全：让编译器去编译刚才创建的引导源文件
MyDebugToolPrefs_FILES = RootListController.m
MyDebugToolPrefs_RESOURCES = layout.xml

MyDebugToolPrefs_INSTALL_PATH = /Library/PreferenceBundles
MyDebugToolPrefs_FRAMEWORKS = UIKit
MyDebugToolPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS)/makefiles/bundle.mk
