name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Setup Theos environment
      uses: Randomblock1/theos-action@v1

    - name: Compile and Package
      run: |
        make package
        
    - name: Upload 成品 DEB 大包
      uses: actions/upload-artifact@v4
      with:
        name: my-completed-deb
        path: packages/*.deb
